# coding: utf-8

"""
    DirectoryService

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Employee(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'fullname': 'str',
        'job_title': 'str',
        'location': 'str',
        'badges': 'list[str]'
    }

    attribute_map = {
        'id': 'id',
        'fullname': 'fullname',
        'job_title': 'jobTitle',
        'location': 'location',
        'badges': 'badges'
    }

    def __init__(self, id=None, fullname=None, job_title=None, location=None, badges=None):  # noqa: E501
        """Employee - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._fullname = None
        self._job_title = None
        self._location = None
        self._badges = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if fullname is not None:
            self.fullname = fullname
        if job_title is not None:
            self.job_title = job_title
        if location is not None:
            self.location = location
        if badges is not None:
            self.badges = badges

    @property
    def id(self):
        """Gets the id of this Employee.  # noqa: E501


        :return: The id of this Employee.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Employee.


        :param id: The id of this Employee.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def fullname(self):
        """Gets the fullname of this Employee.  # noqa: E501


        :return: The fullname of this Employee.  # noqa: E501
        :rtype: str
        """
        return self._fullname

    @fullname.setter
    def fullname(self, fullname):
        """Sets the fullname of this Employee.


        :param fullname: The fullname of this Employee.  # noqa: E501
        :type: str
        """

        self._fullname = fullname

    @property
    def job_title(self):
        """Gets the job_title of this Employee.  # noqa: E501


        :return: The job_title of this Employee.  # noqa: E501
        :rtype: str
        """
        return self._job_title

    @job_title.setter
    def job_title(self, job_title):
        """Sets the job_title of this Employee.


        :param job_title: The job_title of this Employee.  # noqa: E501
        :type: str
        """

        self._job_title = job_title

    @property
    def location(self):
        """Gets the location of this Employee.  # noqa: E501


        :return: The location of this Employee.  # noqa: E501
        :rtype: str
        """
        return self._location

    @location.setter
    def location(self, location):
        """Sets the location of this Employee.


        :param location: The location of this Employee.  # noqa: E501
        :type: str
        """

        self._location = location

    @property
    def badges(self):
        """Gets the badges of this Employee.  # noqa: E501


        :return: The badges of this Employee.  # noqa: E501
        :rtype: list[str]
        """
        return self._badges

    @badges.setter
    def badges(self, badges):
        """Sets the badges of this Employee.


        :param badges: The badges of this Employee.  # noqa: E501
        :type: list[str]
        """

        self._badges = badges

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Employee, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Employee):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
